
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  sql:
    init:
      mode: always

  datasource:
    url: "jdbc:sqlite:./mydatabase.db"
    driver-class-name: org.sqlite.JDBC
    username:
    password:

mybatis:
  type-aliases-package: com.santa.secret.model
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    path: log
