
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  sql:
    init:
      mode: always

  datasource:
    url: "jdbc:sqlite:./mydatabase.db"
    driver-class-name: org.sqlite.JDBC
    username:
    password:

mybatis:
  type-aliases-package: com.santa.secret.model
  mapper-locations: classpath:mapper/*.xml
